name: Cafe Sync

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get source sha
        run: curl https://gitee.com/api/v5/repos/vhik/awesome-cn-share-data/branches/tea --silent | grep "sha" | head -n1 > sha

      - name: Update source sha
        uses: EndBug/add-and-commit@v4
        with:
          message: "chore: 每日更新 gitee 分支为 tea 的数据，存 sha"
          add: "sha"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
